"""Report assembly: findings and scores into one JSON document and its
Markdown twin. Neither carries a timestamp; the fleet fingerprint changes
only when a repository's tree does, so an unchanged fleet re-reports
byte-identically."""

import hashlib
from typing import Dict, List

from .. import ENGINE_VERSION
from .finding import Finding
from .health import HEALTH_WEIGHTS, grade, rank

SEVERITY_ORDER = {"error": 0, "warn": 1, "info": 2}


def build_report(results: List[Dict]) -> Dict:
    """
    Assemble the fleet report.

    `results` is one entry per repository:
    `{name, repo, url, kind, manifest, findings: [Finding], health: {...}}`.
    """
    by_name = {r["name"]: r for r in results}
    scored = {name: r["health"] for name, r in by_name.items() if r.get("health")}
    ordered = rank(scored)

    severity_totals = {"error": 0, "warn": 0, "info": 0}
    check_totals: Dict[str, int] = {}
    for result in results:
        for finding in result["findings"]:
            severity_totals[finding.severity] = severity_totals.get(finding.severity, 0) + 1
            check_totals[finding.check] = check_totals.get(finding.check, 0) + 1

    scores = [r["health"]["score"] for r in results if r.get("health")]
    fingerprint = hashlib.sha256("\n".join(
        f"{r['name']}:{(r.get('manifest') or {}).get('fingerprint', '')}"
        for r in sorted(results, key=lambda x: x["name"])
    ).encode("utf-8")).hexdigest()[:16]

    return {
        "schema_version": "1.0",
        "engine_version": ENGINE_VERSION,
        "fingerprint": fingerprint,
        "summary": {
            "repositories": len(results),
            "gathered": sum(1 for r in results if not (r.get("manifest") or {}).get("error")),
            "findings": sum(len(r["findings"]) for r in results),
            "by_severity": severity_totals,
            "by_check": dict(sorted(check_totals.items())),
            "mean_score": round(sum(scores) / len(scores), 1) if scores else 0,
            "weights": HEALTH_WEIGHTS,
        },
        "ranking": ordered,
        "repositories": {
            r["name"]: {
                "repo": r["repo"], "url": r["url"], "kind": r.get("kind", "default"),
                "head": (r.get("manifest") or {}).get("head", {}),
                "counts": (r.get("manifest") or {}).get("counts", {}),
                "stack": (r.get("manifest") or {}).get("stack", []),
                "health": r.get("health", {}),
                "findings": [f.to_dict() for f in sorted(
                    r["findings"],
                    key=lambda f: (SEVERITY_ORDER.get(f.severity, 9), f.check, f.subject))],
                "error": (r.get("manifest") or {}).get("error", ""),
            }
            for r in sorted(results, key=lambda x: x["name"])
        },
    }


def render_markdown(report: Dict) -> str:
    """The human twin of the report."""
    summary = report["summary"]
    lines: List[str] = [
        "---",
        "title: Fleet documentation health",
        "description: >-",
        "  Documentation health for every public repository in the fleet,",
        "  scored from the checks in scripts/context_engine/analyze/.",
        "generated: true",
        "---",
        "<!-- GENERATED by `python3 -m scripts.context_engine survey` - do not hand-edit -->",
        "",
        "# Fleet documentation health",
        "",
        f"**{summary['repositories']}** repositories surveyed, "
        f"**{summary['findings']}** findings "
        f"({summary['by_severity'].get('error', 0)} error, "
        f"{summary['by_severity'].get('warn', 0)} warn, "
        f"{summary['by_severity'].get('info', 0)} info). "
        f"Mean health **{summary['mean_score']}**.",
        "",
        "Scores are 100 minus the weighted penalty of each component: "
        + ", ".join(f"{k} {v}" for k, v in summary["weights"].items()) + ".",
        "",
        "| Repository | Score | Grade | Errors | Warnings | Info | Docs | Stack |",
        "|---|---:|:---:|---:|---:|---:|---:|---|",
    ]
    for name in report["ranking"]:
        entry = report["repositories"][name]
        counts = {"error": 0, "warn": 0, "info": 0}
        for finding in entry["findings"]:
            counts[finding["severity"]] = counts.get(finding["severity"], 0) + 1
        health = entry.get("health") or {}
        lines.append(
            f"| [{name}]({entry['url']}) | {health.get('score', '—')} "
            f"| {health.get('grade', '—')} | {counts['error']} | {counts['warn']} "
            f"| {counts['info']} | {entry.get('counts', {}).get('docs', 0)} "
            f"| {', '.join(entry.get('stack', [])) or '—'} |"
        )

    lines += ["", "## Findings by check", "",
              "| Check | Findings |", "|---|---:|"]
    for check_id, count in summary["by_check"].items():
        lines.append(f"| {check_id} | {count} |")

    lines += ["", "## Per repository", ""]
    for name in report["ranking"]:
        entry = report["repositories"][name]
        health = entry.get("health") or {}
        lines += [f"### {name} — {health.get('score', '—')} ({health.get('grade', '—')})", ""]
        if entry.get("error"):
            lines += [f"Could not gather: `{entry['error']}`", ""]
            continue
        weak = sorted((health.get("components") or {}).items(),
                      key=lambda kv: kv[1]["score"] - kv[1]["weight"])[:3]
        lines.append("Weakest components: "
                     + ", ".join(f"{k} {v['score']}/{v['weight']}" for k, v in weak))
        lines.append("")
        shown = [f for f in entry["findings"] if f["severity"] in ("error", "warn")][:10]
        if shown:
            lines += ["| Severity | Check | Finding |", "|---|---|---|"]
            for finding in shown:
                lines.append(f"| {finding['severity']} | {finding['check']} "
                             f"| {finding['message']} |")
            lines.append("")
    return "\n".join(lines) + "\n"
