"""
Apex assembly (L0 of the pyramid) and generated-surface injection.

Produces:
  - context/README.md      the consolidated README describing the fleet
  - README.md AUTO span    fleet table between AUTO:projects markers
  - docs/index.md          MkDocs site home mirrored from the apex
  - context/SCHEMA.md      schema for the generated context tree

Generated surfaces carry no timestamps so re-runs are diff-stable unless
the underlying facts changed.
"""

import json
from pathlib import Path
from typing import Dict, List, Optional

from . import ENGINE_VERSION
from .ai import AIError, BaseProvider
from .config import (
    APEX_PATH, AUTO_BEGIN, AUTO_END, CONTEXT_DIR, GENERATED_NOTICE,
    ROOT_README_PATH, SITE_INDEX_PATH,
)
from .registry import Registry

PYRAMID_DIAGRAM = """```
        ▲  L0  context/README.md   - consolidated README (apex)
       ▲▲  L1  context/cards/      - one distilled card per project
      ▲▲▲  L2  context/facts/      - structured facts (machine layer)
     ▲▲▲▲  L3  docs/               - aggregated markdown corpus (base)
    ─────  query: context/index/ · CLI `query` · MCP server (mcp/server.py)
```"""


def _short_summary(facts: Dict, limit: int = 110) -> str:
    identity = facts.get("identity") or {}
    text = (facts["project"].get("registry_description")
            or identity.get("summary") or "")
    text = " ".join(text.split())
    return text[: limit - 1] + "…" if len(text) > limit else text


def fleet_table(registry: Registry, facts_by_name: Dict[str, Dict],
                card_base: str = "context/cards/") -> str:
    """Fleet table used in both the apex and the root README AUTO span."""
    rows = [
        "| Project | Kind | Status | Docs | What it is |",
        "|---|---|---|---|---|",
    ]
    for project in registry.active():
        facts = facts_by_name.get(project.name, {})
        corpus = facts.get("corpus") or {}
        card_link = f"{card_base}{project.name}.md"
        rows.append(
            f"| [{project.name}]({card_link}) "
            f"| {project.kind} | {project.status} "
            f"| {corpus.get('file_count', 0)} "
            f"| {_short_summary(facts)} |"
        )
    return "\n".join(rows)


def _fleet_overview(registry: Registry, facts_by_name: Dict[str, Dict],
                    ai: Optional[BaseProvider]) -> str:
    hub = registry.hub or {}
    heuristic = " ".join(str(hub.get("description", "")).split()) or (
        "Consolidated context for the project fleet."
    )
    if ai is None:
        return heuristic
    digest = {
        name: {
            "kind": facts["project"].get("kind"),
            "summary": _short_summary(facts, 160),
        }
        for name, facts in facts_by_name.items()
    }
    prompt = (
        "Write a 2-3 sentence overview paragraph for the consolidated README "
        "of this project fleet - what the fleet collectively covers and how "
        "the pieces relate.\n\nFLEET:\n" + json.dumps(digest, indent=2, sort_keys=True)
    )
    try:
        return ai.complete(prompt, max_tokens=400).strip()
    except AIError as exc:
        print(f"[assembler] AI fleet overview failed, using registry text: {exc}")
        return heuristic


def build_apex(registry: Registry, facts_by_name: Dict[str, Dict],
               ai: Optional[BaseProvider] = None) -> str:
    hub = registry.hub or {}
    overview = _fleet_overview(registry, facts_by_name, ai)
    lines: List[str] = [
        "---",
        'title: "bamr87 - consolidated README"',
        "category: apex",
        "generated: true",
        f"generated_by: context_engine {ENGINE_VERSION}",
        "---",
        GENERATED_NOTICE,
        "",
        f"# {hub.get('name', 'bamr87')} - consolidated README",
        "",
        f"> {overview}",
        "",
        f"Hub: [{hub.get('repo', 'bamr87/bamr87')}]({hub.get('url', 'https://github.com/bamr87/bamr87')})"
        " · This page is the apex of a context pyramid regenerated by"
        " `python3 -m scripts.context_engine build`.",
        "",
        PYRAMID_DIAGRAM,
        "",
        "## The fleet",
        "",
        fleet_table(registry, facts_by_name, card_base="cards/"),
        "",
    ]
    for project in registry.active():
        facts = facts_by_name.get(project.name, {})
        identity = facts.get("identity") or {}
        corpus = facts.get("corpus") or {}
        lines += [
            f"### {identity.get('title') or project.name}",
            "",
            _short_summary(facts, 400) or "(no summary yet)",
            "",
            f"- Repository: [{project.repo}]({project.url})"
            + (f" (branch `{project.branch}`)" if project.branch else ""),
            f"- Card: [context/cards/{project.name}.md](cards/{project.name}.md)"
            f" · Facts: [context/facts/{project.name}.json](facts/{project.name}.json)",
            f"- Corpus: [`docs/{project.name}/`](../docs/{project.name}/)"
            f" ({corpus.get('file_count', 0)} documents)",
        ]
        topics = (facts.get("project") or {}).get("topics") or project.topics
        if topics:
            lines.append(f"- Topics: {', '.join(topics)}")
        lines.append("")

    lines += [
        "## Query this context",
        "",
        "```bash",
        "python3 -m scripts.context_engine query <term>     # search the pyramid",
        "python3 -m scripts.context_engine card <project>   # print a card",
        "python3 -m scripts.context_engine status           # freshness manifest",
        "```",
        "",
        "AI clients connect through the MCP server (`mcp/server.py`, registered",
        "in `.mcp.json`): tools `list_projects`, `get_project`, `search_context`,",
        "`get_readme`, `get_schema`, `context_status`.",
        "",
    ]
    return "\n".join(lines)


def inject_auto_span(table_md: str, readme_path: Path = ROOT_README_PATH) -> bool:
    """Regenerate the AUTO:projects span in the root README. True if changed."""
    text = readme_path.read_text(encoding="utf-8")
    begin = text.find(AUTO_BEGIN)
    end = text.find(AUTO_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError(
            f"{readme_path.name} is missing the {AUTO_BEGIN} / {AUTO_END} markers"
        )
    updated = (
        text[: begin + len(AUTO_BEGIN)]
        + "\n" + GENERATED_NOTICE + "\n" + table_md + "\n"
        + text[end:]
    )
    if updated == text:
        return False
    readme_path.write_text(updated, encoding="utf-8")
    return True


def build_site_index(registry: Registry, facts_by_name: Dict[str, Dict]) -> str:
    """docs/index.md - the MkDocs site home, mirrored from the apex."""
    lines: List[str] = [
        "---",
        "title: Documentation Home",
        "description: Consolidated documentation for the bamr87 project fleet",
        "generated: true",
        "---",
        GENERATED_NOTICE,
        "",
        "# bamr87 documentation",
        "",
        "Aggregated, continuously refreshed documentation for every project in",
        "the [bamr87](https://github.com/bamr87) fleet. This page is generated",
        "from the fleet registry by the README context engine.",
        "",
        "## Documentation by project",
        "",
    ]
    for project in registry.active():
        facts = facts_by_name.get(project.name, {})
        identity = facts.get("identity") or {}
        corpus = facts.get("corpus") or {}
        target = f"{project.name}/{identity.get('readme', '')}".rstrip("/")
        lines += [
            f"### [{identity.get('title') or project.name}]({target})",
            "",
            (_short_summary(facts, 240) or "(no summary yet)")
            + f" *({corpus.get('file_count', 0)} documents)*",
            "",
        ]
    lines += [
        "---",
        "",
        "## Reports",
        "",
        "- [Quality and analysis results](results/index.md)",
        "- [Sitemap](sitemap.md)",
        "",
    ]
    return "\n".join(lines)


def build_context_schema() -> str:
    """SCHEMA.md for the generated context tree."""
    return "\n".join([
        "---",
        'schema: "0.1"',
        "coverage: full",
        "---",
        GENERATED_NOTICE,
        "",
        "# SCHEMA - context",
        "",
        "> The context pyramid: generated distillation of the fleet's docs,",
        "> regenerated by `python3 -m scripts.context_engine build`.",
        "",
        "## Structure",
        "",
        "| entry | kind | purpose | rules |",
        "|---|---|---|---|",
        "| `README.md` | file | L0 apex - the consolidated fleet README | generated |",
        "| `SCHEMA.md` | file | This file | generated |",
        "| `cards/` | dir | L1 - one distilled card per project | generated |",
        "| `facts/` | dir | L2 - structured facts per project | generated |",
        "| `index/` | dir | Query layer - context_index.json + manifest.json | generated |",
        "",
        "## Forbidden",
        "",
        "- No hand edits anywhere under context/ - change the registry, the",
        "  corpus, or the engine and rebuild.",
        "",
    ])


def write_context_tree(apex_md: str, cards: Dict[str, str],
                       facts_by_name: Dict[str, Dict]) -> None:
    """Write the apex, schema, cards, and facts into context/."""
    from .config import CARDS_DIR, FACTS_DIR

    CONTEXT_DIR.mkdir(exist_ok=True)
    CARDS_DIR.mkdir(exist_ok=True)
    FACTS_DIR.mkdir(exist_ok=True)
    APEX_PATH.write_text(apex_md, encoding="utf-8")
    (CONTEXT_DIR / "SCHEMA.md").write_text(build_context_schema(), encoding="utf-8")
    for name, card_md in cards.items():
        (CARDS_DIR / f"{name}.md").write_text(card_md, encoding="utf-8")
    for name, facts in facts_by_name.items():
        (FACTS_DIR / f"{name}.json").write_text(
            json.dumps(facts, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    # Drop artifacts for projects no longer in the registry.
    keep_cards = {f"{name}.md" for name in cards}
    keep_facts = {f"{name}.json" for name in facts_by_name}
    for stale in CARDS_DIR.glob("*.md"):
        if stale.name not in keep_cards:
            stale.unlink()
    for stale in FACTS_DIR.glob("*.json"):
        if stale.name not in keep_facts:
            stale.unlink()


def write_site_index(registry: Registry, facts_by_name: Dict[str, Dict],
                     path: Path = SITE_INDEX_PATH) -> None:
    path.write_text(build_site_index(registry, facts_by_name), encoding="utf-8")
