"""Shared paths and constants for the context engine."""

from pathlib import Path

# Repo root (this file lives at scripts/context_engine/config.py)
ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = ROOT / "_data"
REGISTRY_PATH = DATA_DIR / "projects.yml"
REPOS_TXT_PATH = ROOT / "repos.txt"

DOCS_DIR = ROOT / "docs"                    # L3 corpus (generated by stages 1-3)
DOCS_INDEX_PATH = DOCS_DIR / "docs_index.json"

CONTEXT_DIR = ROOT / "context"              # the pyramid (generated by this engine)
CARDS_DIR = CONTEXT_DIR / "cards"           # L1
FACTS_DIR = CONTEXT_DIR / "facts"           # L2
INDEX_DIR = CONTEXT_DIR / "index"           # query layer
APEX_PATH = CONTEXT_DIR / "README.md"       # L0 - the consolidated README
CONTEXT_INDEX_PATH = INDEX_DIR / "context_index.json"
MANIFEST_PATH = INDEX_DIR / "manifest.json"

ROOT_README_PATH = ROOT / "README.md"
SITE_INDEX_PATH = DOCS_DIR / "index.md"     # MkDocs site home, mirrored from the apex

HOOKS_DIR = ROOT / "hooks.d"
HOOK_STAGES = (
    "pre_build",
    "post_extract",
    "post_synthesize",
    "post_assemble",
    "post_index",
    "post_build",
)

# Markers for the generated span inside the root README (parent-monorepo
# convention: AUTO spans are regenerated, never hand-edited).
AUTO_BEGIN = "<!-- AUTO:projects:begin -->"
AUTO_END = "<!-- AUTO:projects:end -->"

GENERATED_NOTICE = (
    "<!-- GENERATED by scripts/context_engine - do not hand-edit; "
    "run `python3 -m scripts.context_engine build` -->"
)
