#!/usr/bin/env python3
"""Render context/index/freshness.md from the manifest (post_index hook)."""

import json
import os
from pathlib import Path

root = Path(os.environ.get("CONTEXT_ROOT", "."))
manifest_path = root / "context" / "index" / "manifest.json"
if not manifest_path.is_file():
    print("no manifest yet; skipping freshness report")
    raise SystemExit(0)

manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
lines = [
    "# Context freshness",
    "",
    "<!-- GENERATED by hooks.d/post_index/50-freshness-report.py -->",
    "",
    f"- Generated at: `{manifest.get('generated_at')}`",
    f"- Engine: `{manifest.get('engine_version')}` · enrichment: `{manifest.get('enrichment')}`",
    f"- Projects: {manifest.get('project_count')}",
    f"- Corpus index present: {manifest.get('corpus_index_present')}"
    f" (generated {manifest.get('corpus_index_generated_at') or 'n/a'})",
    "",
    "| Project | corpus fingerprint |",
    "|---|---|",
]
for name, fingerprint in sorted((manifest.get("fingerprints") or {}).items()):
    lines.append(f"| {name} | `{fingerprint}` |")

out = root / "context" / "index" / "freshness.md"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out.relative_to(root)}")
